name: build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      # Envs
    env:
      RELEASE_VERSION: ${{ git rev-parse --short "$GITHUB_SHA" }}
      DOCKER_USER: gpoleze
      IMAGE_REPO: speedtest
    steps:
      # Checkout repo
      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          password: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${DOCKER_USER}/${IMAGE_REPO}:latest,${DOCKER_USER}/${IMAGE_REPO}:$RELEASE_VERSION
          platforms: linux/amd64,linux/arm64

