name: build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      # Envs
    env:
      DOCKER_USER: gpoleze
      IMAGE_REPO: speedtest
    steps:
      # Checkout repo
      - name: checkout code
        uses: actions/checkout@v2

      - name: define RELEASE_VERSION env variable
        run: echo "RELEASE_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1.0.1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.IMAGE_REPO }}:latest
          platforms: linux/amd64,linux/arm64

